-- Supabase Database Setup & Initialization Script
-- Paste this script into the SQL Editor of your Supabase Dashboard to instantiate all tables, triggers, and Row Level Security (RLS) policies.

-- 1. CLEANUP (IF NEEDED)
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();
drop table if exists public.messages cascade;
drop table if exists public.conversation_members cascade;
drop table if exists public.conversations cascade;
drop table if exists public.job_applications cascade;
drop table if exists public.jobs cascade;
drop table if exists public.applicants cascade;
drop table if exists public.employers cascade;
drop table if exists public.users cascade;

drop type if exists public.role_type cascade;
drop type if exists public.marital_status_type cascade;
drop type if exists public.gender_type cascade;
drop type if exists public.salary_currency_type cascade;
drop type if exists public.salary_period_type cascade;
drop type if exists public.job_type_enum cascade;
drop type if exists public.work_type_enum cascade;
drop type if exists public.job_level_enum cascade;
drop type if exists public.min_education_enum cascade;
drop type if exists public.application_status_type cascade;

-- 2. CUSTOM TYPES & ENUMS
create type public.role_type as enum ('admin', 'applicant', 'employer');
create type public.marital_status_type as enum ('single', 'married', 'divorced');
create type public.gender_type as enum ('male', 'female', 'other');
create type public.salary_currency_type as enum ('USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'INR', 'NPR');
create type public.salary_period_type as enum ('hourly', 'monthly', 'yearly');
create type public.job_type_enum as enum ('remote', 'hybrid', 'on-site');
create type public.work_type_enum as enum ('full-time', 'part-time', 'contract', 'temporary', 'freelance');
create type public.job_level_enum as enum ('internship', 'entry level', 'junior', 'mid level', 'senior level', 'lead', 'manager', 'director', 'executive');
create type public.min_education_enum as enum ('none', 'high school', 'undergraduate', 'masters', 'phd');
create type public.application_status_type as enum ('applied', 'reviewing', 'shortlisted', 'rejected', 'selected');

-- 3. TABLES CREATION

-- Users Profile Table (linked to auth.users)
create table public.users (
  id uuid references auth.users on delete cascade primary key,
  name varchar(255) not null,
  username varchar(255) unique not null,
  email varchar(255) unique not null,
  role public.role_type not null default 'applicant',
  phone_number varchar(255),
  avatar_url text,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Employers Profile Table (linked to users)
create table public.employers (
  id uuid references public.users on delete cascade primary key,
  name varchar(255),
  description text,
  avatar_url text,
  banner_image_url text,
  organization_type varchar(100),
  team_size varchar(50),
  year_of_establishment integer,
  website_url varchar(255),
  location varchar(255),
  deleted_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Applicants Profile Table (linked to users)
create table public.applicants (
  id uuid references public.users on delete cascade primary key,
  biography text,
  date_of_birth date,
  nationality varchar(100),
  resume_url text,
  avatar_url text,
  marital_status public.marital_status_type,
  gender public.gender_type,
  education jsonb,
  experience jsonb,
  projects jsonb,
  skills text,
  website_url varchar(255),
  location varchar(255),
  deleted_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Jobs Listings Table
create table public.jobs (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  employer_id uuid references public.employers on delete cascade not null,
  description text not null,
  tags text,
  min_salary integer,
  max_salary integer,
  salary_currency public.salary_currency_type,
  salary_period public.salary_period_type,
  location varchar(255),
  job_type public.job_type_enum,
  work_type public.work_type_enum,
  job_level public.job_level_enum,
  experience text,
  min_education public.min_education_enum,
  is_featured boolean default false not null,
  expires_at timestamp with time zone,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Job Applications Table
create table public.job_applications (
  id bigint generated by default as identity primary key,
  job_id bigint references public.jobs on delete cascade not null,
  applicant_id uuid references public.applicants on delete cascade not null,
  name varchar(255) not null,
  email varchar(255) not null,
  phone_number varchar(50),
  resume_url text not null,
  cover_letter text,
  linkedin_url varchar(255),
  github_url varchar(255),
  portfolio_url varchar(255),
  years_of_experience varchar(50),
  status public.application_status_type not null default 'applied',
  employer_notes text,
  applied_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  
  constraint unique_apply unique (job_id, applicant_id),
  constraint job_applications_applicant_id_users_fkey foreign key (applicant_id) references public.users(id) on delete cascade
);

-- Conversations Table
create table public.conversations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null
);

-- Conversation Members Mapping Table
create table public.conversation_members (
  id bigint generated by default as identity primary key,
  conversation_id bigint references public.conversations on delete cascade not null,
  user_id uuid references public.users on delete cascade not null
);

-- Messages Table
create table public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references public.conversations on delete cascade not null,
  sender_id uuid references public.users on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default now() not null
);

-- 4. PROFILE SYNCHRONIZATION TRIGGER FUNCTION (auth.users -> public.users, public.applicants/employers)
create or replace function public.handle_new_user()
returns trigger as $$
declare
  user_role public.role_type;
  full_name varchar(255);
  user_name varchar(255);
  phone varchar(255);
  avatar text;
begin
  user_role := coalesce((new.raw_user_meta_data->>'role')::public.role_type, 'applicant'::public.role_type);
  full_name := coalesce(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'username', split_part(new.email, '@', 1));
  user_name := coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1) || '_' || substr(md5(random()::text), 1, 6));
  phone := coalesce(new.raw_user_meta_data->>'phone_number', '');
  avatar := coalesce(new.raw_user_meta_data->>'avatar_url', '');

  -- Insert into public.users
  insert into public.users (id, name, username, email, role, phone_number, avatar_url)
  values (new.id, full_name, user_name, new.email, user_role, phone, avatar);
  
  -- Insert profile shells depending on user role
  if user_role = 'employer'::public.role_type then
    insert into public.employers (id, name, avatar_url)
    values (new.id, full_name, avatar);
  else
    insert into public.applicants (id, avatar_url)
    values (new.id, avatar);
  end if;

  return new;
end;
$$ language plpgsql security definer;

-- Bind trigger
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 5. ROW LEVEL SECURITY (RLS) & POLICIES

-- Enable RLS
alter table public.users enable row level security;
alter table public.employers enable row level security;
alter table public.applicants enable row level security;
alter table public.jobs enable row level security;
alter table public.job_applications enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;

-- Policies for public.users
create policy "Allow public read access to users profiles" on public.users
  for select using (true);
  
create policy "Allow users to update their own profiles" on public.users
  for update using (auth.uid() = id);

-- Policies for public.employers
create policy "Allow public read access to employers" on public.employers
  for select using (true);

create policy "Allow employers to update their own profile" on public.employers
  for update using (auth.uid() = id);

-- Policies for public.applicants
create policy "Allow profiles to be read by authenticated users" on public.applicants
  for select using (auth.role() = 'authenticated');

create policy "Allow applicants to update their own profile" on public.applicants
  for update using (auth.uid() = id);

-- Policies for public.jobs
create policy "Allow public read access to jobs" on public.jobs
  for select using (true);

create policy "Allow employers to create jobs" on public.jobs
  for insert with check (
    auth.uid() = employer_id 
    and exists (
      select 1 from public.users where id = auth.uid() and role = 'employer'
    )
  );

create policy "Allow employers to update their own jobs" on public.jobs
  for update using (auth.uid() = employer_id);

create policy "Allow employers to delete their own jobs" on public.jobs
  for delete using (auth.uid() = employer_id);

-- Policies for public.job_applications
create policy "Allow applicants to view their own applications" on public.job_applications
  for select using (
    auth.uid() = applicant_id 
    or auth.uid() = (select employer_id from public.jobs where id = job_id)
  );

create policy "Allow applicants to submit applications" on public.job_applications
  for insert with check (
    auth.uid() = applicant_id 
    and exists (
      select 1 from public.users where id = auth.uid() and role = 'applicant'
    )
  );

create policy "Allow employers to update application status" on public.job_applications
  for update using (
    auth.uid() = (select employer_id from public.jobs where id = job_id)
  );

-- Helper function to check conversation membership without RLS infinite recursion
drop function if exists public.is_conversation_member(bigint, uuid);
create or replace function public.is_conversation_member(conv_id bigint, user_uuid uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  return exists (
    select 1 from public.conversation_members
    where conversation_id = conv_id and user_id = user_uuid
  );
end;
$$;

-- Policies for public.conversations & members
create policy "Allow authenticated users to view conversation records" on public.conversations
  for select using (auth.role() = 'authenticated');

create policy "Allow authenticated users to create conversation records" on public.conversations
  for insert with check (auth.role() = 'authenticated');

create policy "Allow members to view conversation member mappings" on public.conversation_members
  for select using (
    public.is_conversation_member(conversation_id, auth.uid())
  );

create policy "Allow authenticated users to create conversation memberships" on public.conversation_members
  for insert with check (auth.role() = 'authenticated');

-- Policies for public.messages
create policy "Allow members to view messages in conversations" on public.messages
  for select using (
    exists (
      select 1 from public.conversation_members where conversation_id = messages.conversation_id and user_id = auth.uid()
    )
  );

create policy "Allow conversation members to post messages" on public.messages
  for insert with check (
    auth.uid() = sender_id
    and exists (
      select 1 from public.conversation_members where conversation_id = messages.conversation_id and user_id = auth.uid()
    )
  );
